try{
    console.log('existe erro?', a)
}catch(e){
    console.log('existe erro!', e)
}
finally{
    console.log('executa de qualquer jeito')
}
